### ISSUE TITLE
"Input doesn't seem to be weather data"

### ISSUE THREAD

**Issue by Forceh91** [drdevlin/ec-weather-js#11]
I'm not sure if it's something I'm doing wrong or not but I'm using `axios` to fetch the data and then trying to parse it but I'm getting the above error.

```
const Weather = require("ec-weather-js");
const express = require("express");
const cors = require("cors");
const axios = require("axios");
const corsOptions = {
  origin: "http://localhost:8080",
  optionsSuccessStatus: 200,
};
const app = express().use(cors(corsOptions));
const port = 8600;

app.get("/api/weather", async (req, res) => {
  axios.get("https://weather.gc.ca/xml/city/on-143_e.xml").then((resp) => {
    const weather = new Weather(resp.data);
    if (!weather) return;
    res.send(weather);
  });
});

app.listen(port);
```

> (node:16204) UnhandledPromiseRejectionWarning: TypeError: Input doesn't seem to be weather data.

Am I just making a stupid mistake and not understanding how axios responds, or was there a change to the XML files EC produce?

**Comment by drdevlin** [comment]
It likely has to do with the format of axios's `data` property. Can you log `resp.data` and see what it looks like? It needs to be the xml file as a string.

**Comment by drdevlin** [comment]
From axios [Request Config](https://axios-http.com/docs/req_config) docs:
```js
// `responseType` indicates the type of data that the server will respond with
// options are: 'arraybuffer', 'document', 'json', 'text', 'stream'
// browser only: 'blob'
responseType: 'json', // default
```
You need to return 'text', not 'json'.

**Comment by drdevlin** [comment]
I also notice that your server is sending the `weather` instance back. This won't work. Although this library is javascript-friendly, it is not JSON-friendly. You should extract any data you need server-side, then send.

**Comment by Forceh91** [comment]
I don't have access to the code right now but taking another look at it
earlier I'm 95% sure the main issue is that I'm trying to pull the wrong
XML file in, whoops!

**Comment by drdevlin** [comment]
> I don't have access to the code right now but taking another look at it earlier I'm 95% sure the main issue is that I'm trying to pull the wrong XML file in, whoops!
> […](#)

Indeed, data needs to come from [https://dd.weather.gc.ca/citypage_weather/xml/](https://dd.weather.gc.ca/citypage_weather/xml/). But also be sure to parse the response as text and extract the data you need server-side.

Preemptively, I should also say that sending `weather.all` back as a response will also not work. `weather.all` is meant to be used for custom transformations of the data, which (in your case) will still need to be performed server-side.

**Comment by Forceh91** [comment]
I've got it working now that I'm actually accessing the correct URL! Thanks for the heads up on the best way to use the data too :)
